/**
 * CLI: scaffold a new OpenCut video project from a template.
 *
 * Usage:
 *   npx ts-node src/cli/init.ts <project-name> [--template facecam|product|text-only]
 */

import fs from "fs";
import path from "path";

const VALID_TEMPLATES = ["facecam", "product", "text-only"] as const;
type Template = (typeof VALID_TEMPLATES)[number];

function parseArgs() {
  const args = process.argv.slice(2);
  const projectName = args[0];
  const templateIdx = args.findIndex((a) => a === "--template");
  const template: Template =
    (templateIdx >= 0 ? (args[templateIdx + 1] as Template) : undefined) ??
    "facecam";

  if (!projectName) {
    console.error("Usage: npx ts-node src/cli/init.ts <project-name> [--template facecam|product|text-only]");
    process.exit(1);
  }

  if (!VALID_TEMPLATES.includes(template)) {
    console.error(`Invalid template "${template}". Valid: ${VALID_TEMPLATES.join(", ")}`);
    process.exit(1);
  }

  return { projectName, template };
}

function kebabToPascal(str: string): string {
  return str
    .split("-")
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
}

function kebabToCamel(str: string): string {
  const pascal = kebabToPascal(str);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

const TEMPLATES: Record<
  Template,
  {
    config: string;
    timeline: string;
    subtitles: string;
    root: string | ((name: string) => string);
    index: string;
    readme: string | ((name: string) => string);
  }
> = {
  facecam: {
    config: `import type { VideoConfig } from "../../engine";

export const CONFIG: VideoConfig = {
  playbackRate: 1.2,
  fps: 30,
  width: 1920,
  height: 1080,
  crossfadeFrames: 10,
  facecamAsset: "facecam.mp4",
  bgMusicAsset: "music.mp3",
  bgMusicVolume: 0.06,
};
`,

    timeline: `import type { TimelineSegment } from "../../engine";

export const TIMELINE: TimelineSegment[] = [
  // ─── HOOK (0–8s) ──────────────────────────────────────────────────────────
  // id: unique identifier for this segment (used in React keys and debugging)
  // type: visual background type — "facecam-full" shows only the speaker
  // facecamStartSec: where this segment begins in the raw facecam footage
  // durationSec: how long this segment lasts in raw seconds (before speedup)
  // faceBubble: position of the circular face-cam bubble; "hidden" = off
  // showSubtitles: whether Whisper captions are rendered
  {
    id: "s01-hook",
    type: "facecam-full",
    facecamStartSec: 0,
    durationSec: 8,
    faceBubble: "hidden",
    showSubtitles: true,
    showTitleCard: true,          // overlay title card at segment start
    keywords: [
      { text: "Hook", startSec: 2, endSec: 6 },
    ],
  },

  // ─── MAIN CONTENT (8–20s) ─────────────────────────────────────────────────
  // overlayText: small text badge (e.g. "8 slides. Branded. Ready.")
  // overlayTextTiming: [start, end] in raw seconds for the badge
  {
    id: "s02-main",
    type: "facecam-full",
    facecamStartSec: 8,
    durationSec: 12,
    faceBubble: "bottom-right",
    showSubtitles: true,
    overlayText: "Your tagline here",
    overlayTextTiming: [8, 14],
    keywords: [
      { text: "Key Concept", startSec: 9, endSec: 13 },
    ],
    callouts: [
      { text: "Pro tip", position: "top-right", delaySec: 2, durationSec: 3 },
    ],
  },

  // ─── OUTRO (20–28s) ───────────────────────────────────────────────────────
  // showEndCard: renders the branded end card (CTA, URL, etc.)
  {
    id: "s03-outro",
    type: "facecam-full",
    facecamStartSec: 20,
    durationSec: 8,
    faceBubble: "hidden",
    showSubtitles: true,
    showEndCard: true,
  },
];
`,

    subtitles: `import type { SubtitleSegment } from "../../engine";

// Auto-generated by: npx ts-node src/cli/transcribe.ts public/facecam.mp4
// Replace with your Whisper output.
export const SUBTITLE_SEGMENTS: SubtitleSegment[] = [];
`,

    root: (name: string) => {
      const compName = kebabToPascal(name);
      const configName = "CONFIG";
      return `import React from "react";
import { Composition } from "remotion";
import { VideoComposition, computeTotalFrames } from "../../engine";
import { ${configName} } from "./config";
import { TIMELINE } from "./timeline";
import { SUBTITLE_SEGMENTS } from "./subtitles";

const totalFrames = computeTotalFrames(TIMELINE, ${configName});

const ${compName}: React.FC = () => (
  <VideoComposition
    timeline={TIMELINE}
    videoConfig={${configName}}
    subtitleSegments={SUBTITLE_SEGMENTS}
    titleCardTitle="${compName}"
    titleCardSubtitle="Your Name"
    endCardTitle="${compName}"
    endCardCtaText="Follow for more"
  />
);

export const RemotionRoot: React.FC = () => (
  <>
    <Composition
      id="${compName}"
      component={${compName}}
      durationInFrames={totalFrames}
      fps={${configName}.fps}
      width={${configName}.width}
      height={${configName}.height}
    />
    <Composition
      id="${compName}Preview"
      component={${compName}}
      durationInFrames={5 * ${configName}.fps}
      fps={${configName}.fps}
      width={${configName}.width}
      height={${configName}.height}
    />
  </>
);
`;
    },

    index: `import { registerRoot } from "remotion";
import { RemotionRoot } from "./Root";

registerRoot(RemotionRoot);
`,

    readme: (name: string) => `# ${name}

OpenCut video project generated with the \`facecam\` template.

## Files

- \`config.ts\` — video settings (resolution, playback rate, assets)
- \`timeline.ts\` — scene-by-scene timeline with overlays
- \`subtitles.ts\` — Whisper-generated word-level captions
- \`Root.tsx\` — Remotion root component (compositions)
- \`index.ts\` — entry point that registers the root

## Required assets (place in \`public/\`)

- \`facecam.mp4\` — primary talking-head footage
- \`music.mp3\` — background music track

## Next steps

1. Replace the placeholder keywords/callouts in \`timeline.ts\` with your actual script.
2. Run transcription to generate \`subtitles.ts\`:
   \`\`\`
   npx ts-node src/cli/transcribe.ts public/facecam.mp4
   \`\`\`
3. Preview in Remotion Studio:
   \`\`\`
   npx remotion studio src/examples/${name}/index.ts
   \`\`\`
4. Render the final video:
   \`\`\`
   npx remotion render src/examples/${name}/index.ts ${kebabToPascal(name)} out/${name}.mp4
   \`\`\`
`,
  },

  product: {
    config: `import type { VideoConfig } from "../../engine";

export const CONFIG: VideoConfig = {
  playbackRate: 1.15,
  fps: 30,
  width: 1920,
  height: 1080,
  crossfadeFrames: 10,
  facecamAsset: "facecam.mp4",
  bgMusicAsset: "music.mp3",
  bgMusicVolume: 0.06,
};
`,

    timeline: `import type { TimelineSegment } from "../../engine";

export const TIMELINE: TimelineSegment[] = [
  // ─── INTRO: facecam + title card ──────────────────────────────────────────
  {
    id: "s01-intro",
    type: "facecam-full",
    facecamStartSec: 0,
    durationSec: 8,
    faceBubble: "hidden",
    showSubtitles: true,
    showTitleCard: true,
    keywords: [
      { text: "Product Demo", startSec: 1, endSec: 5 },
    ],
  },

  // ─── SCREENSHOT: static screen with face bubble ───────────────────────────
  // screenImage: path relative to public/ (required for "screen-static")
  {
    id: "s02-dashboard",
    type: "screen-static",
    facecamStartSec: 8,
    durationSec: 10,
    faceBubble: "bottom-left",
    showSubtitles: true,
    screenImage: "screenshots/dashboard.png",
    overlayText: "Main dashboard overview",
    overlayTextTiming: [8, 14],
  },

  // ─── APP MOCKUP: stylised UI preview ──────────────────────────────────────
  // appMockup: required when type = "app-mockup"
  {
    id: "s03-app",
    type: "app-mockup",
    facecamStartSec: 18,
    durationSec: 10,
    faceBubble: "bottom-right",
    showSubtitles: true,
    appMockup: {
      title: "My App",
      url: "myapp.com",
      tabs: [
        { name: "Overview", active: true },
        { name: "Settings", active: false },
      ],
      rows: [
        { label: "Users", value: "12.4k", score: 94, intent: "positive" },
        { label: "Revenue", value: "$8.2k", score: 87, intent: "positive" },
      ],
      accentColor: "#4ade80",
    },
  },

  // ─── COMPARISON: side-by-side table ───────────────────────────────────────
  // comparison: required when type = "comparison"
  {
    id: "s04-compare",
    type: "comparison",
    facecamStartSec: 28,
    durationSec: 12,
    faceBubble: "bottom-left",
    showSubtitles: true,
    comparison: {
      title: "Why us?",
      subtitle: "Head-to-head feature comparison",
      rows: [
        {
          name: "Competitor A",
          features: { "Auto-sync": false, "AI captions": "Manual", "4K Export": true },
        },
        {
          name: "Our Product",
          features: { "Auto-sync": true, "AI captions": "Whisper", "4K Export": true },
          highlight: true,
        },
      ],
      featureLabels: ["Auto-sync", "AI captions", "4K Export"],
      accentColor: "#4ade80",
    },
  },

  // ─── OUTRO ────────────────────────────────────────────────────────────────
  {
    id: "s05-outro",
    type: "facecam-full",
    facecamStartSec: 40,
    durationSec: 8,
    faceBubble: "hidden",
    showSubtitles: true,
    showEndCard: true,
  },
];
`,

    subtitles: `import type { SubtitleSegment } from "../../engine";

// Auto-generated by: npx ts-node src/cli/transcribe.ts public/facecam.mp4
// Replace with your Whisper output.
export const SUBTITLE_SEGMENTS: SubtitleSegment[] = [];
`,

    root: (name: string) => {
      const compName = kebabToPascal(name);
      return `import React from "react";
import { Composition } from "remotion";
import { VideoComposition, computeTotalFrames } from "../../engine";
import { CONFIG } from "./config";
import { TIMELINE } from "./timeline";
import { SUBTITLE_SEGMENTS } from "./subtitles";

const totalFrames = computeTotalFrames(TIMELINE, CONFIG);

const ${compName}: React.FC = () => (
  <VideoComposition
    timeline={TIMELINE}
    videoConfig={CONFIG}
    subtitleSegments={SUBTITLE_SEGMENTS}
    titleCardTitle="${compName}"
    titleCardSubtitle="Product Demo"
    endCardTitle="${compName}"
    endCardCtaText="Try it free"
    endCardUrl="your-product.com"
  />
);

export const RemotionRoot: React.FC = () => (
  <>
    <Composition
      id="${compName}"
      component={${compName}}
      durationInFrames={totalFrames}
      fps={CONFIG.fps}
      width={CONFIG.width}
      height={CONFIG.height}
    />
    <Composition
      id="${compName}Preview"
      component={${compName}}
      durationInFrames={5 * CONFIG.fps}
      fps={CONFIG.fps}
      width={CONFIG.width}
      height={CONFIG.height}
    />
  </>
);
`;
    },

    index: `import { registerRoot } from "remotion";
import { RemotionRoot } from "./Root";

registerRoot(RemotionRoot);
`,

    readme: (name: string) => `# ${name}

OpenCut video project generated with the \`product\` template.

## Files

- \`config.ts\` — video settings (resolution, playback rate, assets)
- \`timeline.ts\` — scene-by-scene timeline with overlays
- \`subtitles.ts\` — Whisper-generated word-level captions
- \`Root.tsx\` — Remotion root component (compositions)
- \`index.ts\` — entry point that registers the root

## Required assets (place in \`public/\`)

- \`facecam.mp4\` — primary talking-head footage
- \`music.mp3\` — background music track
- \`screenshots/dashboard.png\` — static screenshot for screen-static segment

## Next steps

1. Replace the placeholder \`appMockup\` and \`comparison\` data in \`timeline.ts\`.
2. Add your screenshots to \`public/screenshots/\` and update paths.
3. Run transcription to generate \`subtitles.ts\`:
   \`\`\`
   npx ts-node src/cli/transcribe.ts public/facecam.mp4
   \`\`\`
4. Preview in Remotion Studio:
   \`\`\`
   npx remotion studio src/examples/${name}/index.ts
   \`\`\`
`,
  },

  "text-only": {
    config: `import type { VideoConfig } from "../../engine";

export const CONFIG: VideoConfig = {
  playbackRate: 1.0,
  fps: 30,
  width: 1920,
  height: 1080,
  crossfadeFrames: 10,
  facecamAsset: "narration.mp4",   // optional narration footage; set to "" if unused
  bgMusicAsset: "music.mp3",
  bgMusicVolume: 0.08,
};
`,

    timeline: `import type { TimelineSegment } from "../../engine";

export const TIMELINE: TimelineSegment[] = [
  // ─── KINETIC TYPOGRAPHY INTRO ─────────────────────────────────────────────
  // kineticText: required when type = "kinetic-text"
  // highlightWords: optional list of words to accent
  // backgroundEffect: generative backdrop (orbs, particles, grid, waves, dots)
  {
    id: "s01-kinetic-intro",
    type: "kinetic-text",
    facecamStartSec: 0,
    durationSec: 6,
    faceBubble: "hidden",
    showSubtitles: false,
    kineticText: {
      text: "Big Ideas",
      highlightWords: ["Big"],
      accentColor: "#4ade80",
    },
    backgroundEffect: {
      type: "particles",
      accentColor: "#4ade80",
      intensity: 0.6,
      particleCount: 50,
    },
  },

  // ─── SECOND KINETIC LINE ──────────────────────────────────────────────────
  {
    id: "s02-kinetic-body",
    type: "kinetic-text",
    facecamStartSec: 6,
    durationSec: 8,
    faceBubble: "hidden",
    showSubtitles: false,
    kineticText: {
      text: "Explained in Motion",
      highlightWords: ["Motion"],
      accentColor: "#60a5fa",
    },
    backgroundEffect: {
      type: "waves",
      accentColor: "#60a5fa",
      intensity: 0.5,
    },
  },

  // ─── OUTRO WITH END CARD ──────────────────────────────────────────────────
  {
    id: "s03-outro",
    type: "kinetic-text",
    facecamStartSec: 14,
    durationSec: 6,
    faceBubble: "hidden",
    showSubtitles: false,
    showEndCard: true,
    kineticText: {
      text: "Thanks for watching",
      accentColor: "#fbbf24",
    },
    backgroundEffect: {
      type: "orbs",
      accentColor: "#fbbf24",
      intensity: 0.5,
      orbCount: 2,
    },
  },
];
`,

    subtitles: `import type { SubtitleSegment } from "../../engine";

// Text-only projects usually don't use subtitles, but you can add them
// if you have a narration track. Generate with:
//   npx ts-node src/cli/transcribe.ts public/narration.mp4
export const SUBTITLE_SEGMENTS: SubtitleSegment[] = [];
`,

    root: (name: string) => {
      const compName = kebabToPascal(name);
      return `import React from "react";
import { Composition } from "remotion";
import { VideoComposition, computeTotalFrames } from "../../engine";
import { CONFIG } from "./config";
import { TIMELINE } from "./timeline";
import { SUBTITLE_SEGMENTS } from "./subtitles";

const totalFrames = computeTotalFrames(TIMELINE, CONFIG);

const ${compName}: React.FC = () => (
  <VideoComposition
    timeline={TIMELINE}
    videoConfig={CONFIG}
    subtitleSegments={SUBTITLE_SEGMENTS}
    titleCardTitle="${compName}"
    titleCardSubtitle="Kinetic Typography"
    endCardTitle="${compName}"
    endCardCtaText="Learn more"
    endCardUrl="your-site.com"
  />
);

export const RemotionRoot: React.FC = () => (
  <>
    <Composition
      id="${compName}"
      component={${compName}}
      durationInFrames={totalFrames}
      fps={CONFIG.fps}
      width={CONFIG.width}
      height={CONFIG.height}
    />
    <Composition
      id="${compName}Preview"
      component={${compName}}
      durationInFrames={5 * CONFIG.fps}
      fps={CONFIG.fps}
      width={CONFIG.width}
      height={CONFIG.height}
    />
  </>
);
`;
    },

    index: `import { registerRoot } from "remotion";
import { RemotionRoot } from "./Root";

registerRoot(RemotionRoot);
`,

    readme: (name: string) => `# ${name}

OpenCut video project generated with the \`text-only\` template.

## Files

- \`config.ts\` — video settings (resolution, playback rate, assets)
- \`timeline.ts\` — scene-by-scene timeline with kinetic typography
- \`subtitles.ts\` — optional Whisper captions (empty by default)
- \`Root.tsx\` — Remotion root component (compositions)
- \`index.ts\` — entry point that registers the root

## Required assets (place in \`public/\`)

- \`music.mp3\` — background music track
- \`narration.mp4\` (optional) — if you want subtitles or background video

## Next steps

1. Edit \`kineticText.text\` and \`highlightWords\` in \`timeline.ts\`.
2. Tweak \`backgroundEffect\` (try \`orbs\`, \`particles\`, \`grid\`, \`waves\`, \`dots\`).
3. Preview in Remotion Studio:
   \`\`\`
   npx remotion studio src/examples/${name}/index.ts
   \`\`\`
4. Render the final video:
   \`\`\`
   npx remotion render src/examples/${name}/index.ts ${kebabToPascal(name)} out/${name}.mp4
   \`\`\`
`,
  },
};

function writeFile(filePath: string, content: string) {
  fs.writeFileSync(filePath, content, "utf-8");
  console.log(`  created ${filePath}`);
}

function main() {
  const { projectName, template } = parseArgs();
  const projectRoot = path.resolve(__dirname, "../..");
  const examplesDir = path.join(projectRoot, "src/examples");
  const projectDir = path.join(examplesDir, projectName);

  if (fs.existsSync(projectDir)) {
    console.error(`❌ Directory already exists: ${projectDir}`);
    process.exit(1);
  }

  fs.mkdirSync(projectDir, { recursive: true });

  const t = TEMPLATES[template];

  writeFile(path.join(projectDir, "config.ts"), t.config);
  writeFile(path.join(projectDir, "timeline.ts"), t.timeline);
  writeFile(path.join(projectDir, "subtitles.ts"), t.subtitles);
  writeFile(path.join(projectDir, "Root.tsx"), typeof t.root === "function" ? t.root(projectName) : t.root);
  writeFile(path.join(projectDir, "index.ts"), t.index);
  writeFile(path.join(projectDir, "README.md"), typeof t.readme === "function" ? t.readme(projectName) : t.readme);

  console.log(`\n✅ Created "${projectName}" (${template} template) at src/examples/${projectName}/`);
  console.log("\nNext steps:");
  console.log(`  1. Add assets to public/ (facecam video, music, screenshots, etc.)`);
  console.log(`  2. Customize timeline.ts and config.ts`);
  console.log(`  3. Run: npx ts-node src/cli/validate.ts src/examples/${projectName}/timeline.ts`);
  console.log(`  4. Preview:  npx remotion studio src/examples/${projectName}/index.ts`);
  console.log(`  5. Render:   npx remotion render src/examples/${projectName}/index.ts ${kebabToPascal(projectName)} out/${projectName}.mp4`);
}

main();
